<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ServiceRequestSeeder extends Seeder
{
    public function run(): void
    {
        $userIds = DB::table('users')->pluck('id')->toArray();
        $serviceTypeIds = DB::table('service_type')->pluck('service_type_id')->toArray();
        $districtIds = DB::table('district')->pluck('district_id')->toArray();
        $statuses = ['pending', 'processed', 'approved', 'rejected', 'cancelled', 'pending'];

        foreach ($statuses as $index => $status) {
            $requestId = DB::table('service_request')->insertGetId([
                'request_number' => 'SRV-20260626000' . ($index + 1),
                'user_id' => $userIds[array_rand($userIds)],
                'service_type_id' => $serviceTypeIds[array_rand($serviceTypeIds)],
                'district_id' => $districtIds[array_rand($districtIds)],
                'applicant_name' => 'Applicant ' . ($index + 1),
                'applicant_nik' => '123456789012345' . ($index + 1),
                'applicant_phone' => '08123456789' . $index,
                'applicant_address' => 'Address ' . ($index + 1),
                'purpose' => 'Purpose ' . ($index + 1),
                'status' => $status,
                'submitted_at' => Carbon::now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            DB::table('service_request_history')->insert([
                'service_request_id' => $requestId,
                'user_id' => $userIds[0],
                'previous_status' => null,
                'new_status' => $status,
                'notes' => 'Generated by seeder',
                'changed_at' => Carbon::now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
